### ISSUE TITLE
Windows dependent build.xml file leads to failed build

### ISSUE THREAD

**Issue by hyder** [remeniuk/sbt-netbeans-plugin#1]
The build.xml file is Windows-dependent. In particular, it's looking for "sbt.bat". This leads to failed build on non-Windows systems.

It should only look for the sbt in the path.

**Comment by remeniuk** [comment]
"sbt" without an extension will work only on *nix. 
I've modified build.xml generation the way that "sbt" is used for *nix, and "sbt.bat" for win.
Please check master or http://remeniuk.github.com/maven/ (v0.0.3) for the update.
