### ISSUE TITLE
java.lang.NoSuchMethodError: sbt.Command$.apply$default$2()Lsbt/Help

### ISSUE THREAD

**Issue by jilen** [remeniuk/sbt-netbeans-plugin#17]
when i add this plugin into project/plugins/build.sbt this error is reported my build.sbt looks like this

resolvers ++= Seq(
        Classpaths.typesafeResolver,
        "remeniuk repo" at "http://remeniuk.github.com/maven" )

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse" % "1.4.0")

libraryDependencies += "org.netbeans" %% "sbt-netbeans-plugin" % "0.1.4"

**Comment by jilen** [comment]
that is because i am using sbt 0.11.0 . Very sorry about the misetake

**Comment by remeniuk** [comment]
No problem! Plugin's version 0.1.3 is for SBT 0.11.
